
% clc
% clear all
close all 

nodeIDs   = {...
                '001e06323a12',...
                '001e06318cd1',...
                '001e06305a61',...
                '001e06323a05',...
                '001e06305a57',...
                '001e063059c2',...
                '001e06318c28',...
                '001e06305a6b',...
                '001e063239e3',...
                '001e06305a6c'...
                };
                        
mintsInputsPalas = {...
    'temperature_BME280'           ,...
    'pressure_BME280'              ,...
    'humidity_BME280'              ,...
    'nh3_MGS001'                   ,...
    'co_MGS001'                    ,...
    'no2_MGS001'                   ,...
    'c3h8_MGS001'                  ,...
    'c4h10_MGS001'                 ,...
    'ch4_MGS001'                   ,...
    'h2_MGS001'                    ,...
    'c2h5oh_MGS001'                ,...
    'binCount0_OPCN2'              ,...
    'binCount1_OPCN2'              ,...
    'binCount2_OPCN2'              ,...
    'binCount3_OPCN2'              ,...
    'binCount4_OPCN2'              ,...
    'binCount5_OPCN2'              ,...
    'binCount6_OPCN2'              ,...
    'binCount7_OPCN2'              ,...
    'binCount8_OPCN2'              ,...
    'binCount9_OPCN2'              ,...
    'binCount10_OPCN2'             ,...
    'binCount11_OPCN2'             ,...
    'binCount12_OPCN2'             ,...
    'binCount13_OPCN2'             ,...
    'binCount14_OPCN2'             ,...
    'binCount15_OPCN2'             ,...
    'bin1TimeToCross_OPCN2'        ,...
    'bin3TimeToCross_OPCN2'        ,...
    'bin5TimeToCross_OPCN2'        ,...
    'bin7TimeToCross_OPCN2'        ,...
    'PM10_OPCN2'                   ,...
    'PM1_OPCN2'                    ,...
    'PM2_5_OPCN2'                  ,...
    'c02_SCD30'                    ,...
    'temperature_SCD30'            ,...
    'humidity_SCD30'               };


mintsInputLabelsPalas = {...
    'Temperature BME280'               ,...
    'Pressure BME280'                  ,...
    'Humidity BME280'                  ,...
    'NH_{3} MGS'                       ,...
    'CO MGS001'                        ,...
    'NO_{2} MGS'                       ,...
    'C_{3}H_8 MGS'                     ,...
    'C_{4}H_{10}MGS'                   ,...
    'CH_{4} MGS'                       ,...
    'H_{2} MGS'                        ,...
    'C_{2}H_{5}OH MGS'                 ,...
    'Bin Count 0 OPCN2'                ,...
    'Bin Count 1 OPCN2'                ,...
    'Bin Count 2 OPCN2'                ,...
    'Bin Count 3 OPCN2'                ,...
    'Bin Count 4 OPCN2'                ,...
    'Bin Count 5 OPCN2'                ,...
    'Bin Count 6 OPCN2'                ,...
    'Bin Count 7 OPCN2'                ,...
    'Bin Count 8 OPCN2'                ,...
    'Bin Count 9 OPCN2'                ,...
    'Bin Count 10 OPCN2'               ,...
    'Bin Count 11 OPCN2'               ,...
    'Bin Count 12 OPCN2'               ,...
    'Bin Count 13 OPCN2'               ,...
    'Bin Count 14 OPCN2'               ,...
    'Bin Count 15 OPCN2'               ,...
    'Bin 1 Time to Cross OPCN2'        ,...
    'Bin 3 Time to Cross OPCN2'        ,...
    'Bin 5 Time to Cross OPCN2'        ,...
    'Bin 7 Time to Cross OPCN2'        ,...
    'PM_{10} OPCN2'                    ,...
    'PM_{1} OPCN2'                     ,...
    'PM_{2.5} OPCN2'                   ,...
    'CO_{2} SCD30'                     ,...
    'Temperature SCD30'                ,...
    'Humidity SCD30'                  ...
     };

mintsInputsAirMar = {...
    'temperature_BME280'           ,...
    'pressure_BME280'              ,...
    'humidity_BME280'              ,...
    'temperature_SCD30'            ,...
    'humidity_SCD30'               };


mintsInputLabelsAirMar = {...
    'Temperature BME280'               ,...
    'Pressure BME280'                  ,...
    'Humidity BME280'                  ,...
    'Temperature SCD30'                ,...
    'Humidity SCD30'                  ...
     }; 
 
 
 
mintsTargets =   {...
                    'pm1_PALAS'                       ,...
                    'pm2_5_palas'                     ,...
                    'pm4_palas'                       ,...
                    'pm10_palas'                      ,...
                    'pmTotal_palas'                   ,...
                    'dCn_palas'                       ,...
                    'pressureBars_YXXDR'   ,...
                    'airTemperature_WIMDA'            ,...
                    'relativeHumidity_WIMDA'          ,...
                    'dewPoint_WIMDA'                 ...
                     };

        
mintsTargetLabels =   {...
                    'PM_{1}'                  ,...
                    'PM_{2.5}'                ,...
                    'PM_{4}'                  ,...
                    'PM_{10}'                 ,...
                    'PM_{Total}'              ,...
                    'Particle Concentration'   ,...
                    'Pressure'                 ,...
                    'Temperature'              ,...
                    'Humidity'                  ,...
                    'Dew Point'                 ...
                    } ;
mintsMdlVersions =   {...
                    '2020_05_07'               ,...
                    '2020_05_07'               ,...
                    '2020_05_07'               ,...
                    '2020_05_07'               ,...
                    '2020_05_07'               ,...
                    '2020_05_07'               ,...
                    '2020_05_10'                 ,...
                    '2020_05_08'              ,...
                    '2020_05_08'                ,...
                    '2020_05_08'                ...
                    } ;

wantedVariables =      {...
                        'latitudeCoordinate_GPSGPGGA2'    ,...
                        'longitudeCoordinate_GPSGPGGA2'   ,...
                        'altitude_GPSGPGGA2'              ,...
                        'binCount0_OPCN2'                 ,...
                        'binCount1_OPCN2'                 ,...
                        'binCount2_OPCN2'                 ,...
                        'binCount3_OPCN2'                 ,...
                        'binCount4_OPCN2'                 ,...
                        'binCount5_OPCN2'                 ,...
                        'binCount6_OPCN2'                 ,...
                        'binCount7_OPCN2'                 ,...
                        'binCount8_OPCN2'                 ,...
                        'binCount9_OPCN2'                 ,...
                        'binCount10_OPCN2'                ,...
                        'binCount11_OPCN2'                ,...
                        'binCount12_OPCN2'                ,...
                        'binCount13_OPCN2'                ,...
                        'binCount14_OPCN2'                ,...
                        'binCount15_OPCN2'                ,...
                        'pm1_PALAS_Predicted'             ,...
                        'pm2_5_palas_Predicted'           ,...
                        'pm4_palas_Predicted'             ,...
                        'pm10_palas_Predicted'            ,...
                        'pmTotal_palas_Predicted'         ,...
                        'dCn_palas_Predicted'             ,...
                        'pressureBars_YXXDR_Predicted'    ,...
                        'airTemperature_WIMDA_Predicted'  ,...
                        'relativeHumidity_WIMDA_Predicted',...
                        'dewPoint_WIMDA_Predicted'        ...
                        };
wantedVariableLabels =      {...
                        'Latitude'    ,...
                        'Longitude'   ,...
                        'Altitude'    ,...
                        'Bin0'        ,...
                        'Bin1'        ,...
                        'Bin2'        ,...
                        'Bin3'        ,...
                        'Bin4'        ,...
                        'Bin5'        ,...
                        'Bin6'        ,...
                        'Bin7'        ,...
                        'Bin8'        ,...
                        'Bin9'        ,...
                        'Bin10'       ,...
                        'Bin11'       ,...
                        'Bin12'       ,...
                        'Bin13'       ,...
                        'Bin14'       ,...
                        'Bin15'       ,...
                        'PM1'         ,...
                        'PM2_5'       ,...
                        'PM4'         ,...
                        'PM10'        ,...
                        'PMTotal'     ,...
                        'ParticleConcentration'             ,...
                        'Pressure'     ,...
                        'Temperature'  ,...
                        'Humidity'     ,...
                        'DewPoint'...
                        };
            
for nodeIndex  = 1: length(nodeIDs)
    nodeID = string(nodeIDs(nodeIndex));
    for n  = 1:length(mintsTargets) 
        eval(strcat('mintsNode_',nodeID,'(n,1).target =  mintsTargets{n};'))
        eval(strcat('mintsNode_',nodeID,'(n,1).targetLabel      =  mintsTargetLabels{n};')) 
        eval(strcat('mintsNode_',nodeID,'(n,1).modelVersion      =  mintsMdlVersions{n};'))
        if n<= 6
            eval(strcat('mintsNode_',nodeID,'(n,1).inputs           =  mintsInputsPalas;'))
            eval(strcat('mintsNode_',nodeID,'(n,1).inputLabels      =  mintsInputLabelsPalas;'))
        else
            eval(strcat('mintsNode_',nodeID,'(n,1).inputs           =  mintsInputsAirMar;'))
            eval(strcat('mintsNode_',nodeID,'(n,1).inputLabels      =  mintsInputLabelsAirMar;'))
        end 
    end
end

