function outCalibrated = printCSVDailyLive(mintsDailyRetimed,...
                            wantedVariables,wantedVariableLabels,...
                            calibratedFolder,nodeID,...
                            period,dateIndex,stringIn)
%PRINTCSVDAILY Summary of this function goes here

     currentDate         = period(dateIndex);
     outCalibrated= mintsDailyRetimed(:,wantedVariables);
     outCalibrated.Properties.VariableNames= wantedVariableLabels;
     
     outCalibrated.dateTime.Format = 	'yyyy-MM-dd''T''HH:mm:ss';
     
     outCalibrated.PM1(outCalibrated.PM1>outCalibrated.PM2_5)   = ...
            outCalibrated.PM2_5(outCalibrated.PM1>outCalibrated.PM2_5);
        
     outCalibrated.PM2_5(outCalibrated.PM2_5>outCalibrated.PM4) = ...
            outCalibrated.PM4(outCalibrated.PM2_5>outCalibrated.PM4);
        
     outCalibrated.PM4(outCalibrated.PM4>outCalibrated.PM10)    = ...
            outCalibrated.PM10(outCalibrated.PM4>outCalibrated.PM10);

                                             
     outCalibratedFileName    = strcat(calibratedFolder,"/",nodeID,"/",...
                                                     num2str(year(currentDate),'%04d'),"/",...
                                                     num2str(month(currentDate),'%02d'),"/",...
                                                     num2str(day(currentDate),'%02d'),"/",...
                                                     "MINTS_",...
                                                     nodeID,...
                                                     "_",stringIn,"_",...
                                                     num2str(year(currentDate),'%02d'),"_",...
                                                     num2str(month(currentDate),'%02d'),"_",...
                                                     num2str(day(currentDate),'%02d'),".csv"...
                                                 );  
    if ~exist(fileparts(outCalibratedFileName), 'dir')
        mkdir(fileparts(outCalibratedFileName));
    end

    writetimetable(outCalibrated,outCalibratedFileName)
end

